// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJEUUbp55Rz6MkSO0XTexlpss8ZKnar5k',
    appId: '1:215789729164:web:99c33b349c7ada190692a9',
    messagingSenderId: '215789729164',
    projectId: 'lab-doctor',
    authDomain: 'lab-doctor.firebaseapp.com',
    storageBucket: 'lab-doctor.firebasestorage.app',
    measurementId: 'G-70TT4VGQJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGwkJ0l_gBizR3-XfBCJqgPPfxlAjlvCM',
    appId: '1:215789729164:android:48ef1eeeb9ad38610692a9',
    messagingSenderId: '215789729164',
    projectId: 'lab-doctor',
    storageBucket: 'lab-doctor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKWLbHCZ40Tg8rI3B6iUtpek5alf4mpzo',
    appId: '1:215789729164:ios:819e61b30e4839f90692a9',
    messagingSenderId: '215789729164',
    projectId: 'lab-doctor',
    storageBucket: 'lab-doctor.firebasestorage.app',
    androidClientId: '215789729164-mpri78glt8at4htneraek9sobrcit3h0.apps.googleusercontent.com',
    iosClientId: '215789729164-1r00ocad17hej75ia7qhn94pj9eqthi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.labdoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKWLbHCZ40Tg8rI3B6iUtpek5alf4mpzo',
    appId: '1:215789729164:ios:819e61b30e4839f90692a9',
    messagingSenderId: '215789729164',
    projectId: 'lab-doctor',
    storageBucket: 'lab-doctor.firebasestorage.app',
    androidClientId: '215789729164-mpri78glt8at4htneraek9sobrcit3h0.apps.googleusercontent.com',
    iosClientId: '215789729164-1r00ocad17hej75ia7qhn94pj9eqthi1.apps.googleusercontent.com',
    iosBundleId: 'com.example.labdoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJEUUbp55Rz6MkSO0XTexlpss8ZKnar5k',
    appId: '1:215789729164:web:0f471ded1c9e77f60692a9',
    messagingSenderId: '215789729164',
    projectId: 'lab-doctor',
    authDomain: 'lab-doctor.firebaseapp.com',
    storageBucket: 'lab-doctor.firebasestorage.app',
    measurementId: 'G-F7GH01JRFZ',
  );
}
